apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: test-sopssecret-05
  namespace: default
spec:
  secretTemplates:
    - name: test-partially-encrypted-05
      stringData:
        PLAIN_CONFIG_VALUE: someConfigValue
        SECRET_TOKEN: someSecretToken
