apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: test-sopssecret-05
    namespace: default
spec:
    secretTemplates:
        - name: test-partially-encrypted-05
          stringData:
            PLAIN_CONFIG_VALUE: someConfigValue
            SECRET_TOKEN: ENC[AES256_GCM,data:ggy07/8dqSNCv4npxc+b,iv:WG3SuqlyFl4pGBIJMIiHQW94DLcTDRUPxnDRs/ZhA5U=,tag:bLqhcNzcsHKM0hPFGeHbgA==,type:str]
sops:
    age:
        - recipient: age1pnmp2nq5qx9z4lpmachyn2ld07xjumn98hpeq77e4glddu96zvms9nn7c8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVUIxMXNKNjlYaUV3ZXBi
            d2ovOGFuc08zdjdZaUIrSzhVd3lIWmRNUGxvCkVDd1JhNk5YaDlxR0ZmREY5U1pq
            b3BGSDFsMkZJcUFhTGdDSkJkclFnMUEKLS0tIE95KzlidDBEMzFNcm1lSEFndGk0
            UFp0djdsVzYzMjNOaS85VUxJZ1hoNzAKg35Sg4i4vfbgRSxa5IEDWHSpmPvub+MZ
            coAydWK2qGY2PukquJHYAJkdMvYG81m1p1X8s+a8ZU1k3bQewtO2OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T22:49:48Z"
    mac: ENC[AES256_GCM,data:VE2QaKCnp0wUgFZYg/p13P25306NDaOONsPzw+DtIJZE87cku1h/7Ej/tRJ5yPzukynn9PL+kEJe0GxTiFtIN7WJ7k8Oyuqt5Le++tMtl/72NvlTcyghYX4i42CbkGi943FlJ7ZWS/Qm102Kt7Wzdv6JiagDkhV6yuopn5hU9t4=,iv:GtuTXoGCaHxb7pGTV/Ns5GxZmP0jHES1nguXiJ8bFXE=,tag:uMf5KWHCTwnmFM4O1eesyg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|status|name|PLAIN_CONFIG_VALUE)$
    version: 3.11.0
